---
# tasks file for mapr_license

    - name: get the list of licenses, filter for description
      sudo: yes
      sudo_user: '{{mapr_admin_username}}'
      run_once: yes
      shell: maprcli license list -json | grep 'description":' | grep -v Base
      register: license_descriptions
      failed_when: license_descriptions.rc not in (0,1)
      changed_when: false

    - name: install a license key
      sudo: yes
      sudo_user: mapr
      command: maprcli license add -license '{{ lookup('file', license_file) }}'
      run_once: yes
      notify: 
        - start NFS gateways
        - start standby CLDBs
      when: license_file != None and license_file|length > 0  and inventory_hostname == groups["cldb"][0] and license_descriptions.rc == 1 # grep returned 1, so no non-Base license found

