---
# tasks file for mapr_license
# supply the path to the license file in extra-vars:
# ansible-playbook -i playbooks/cluster.hosts -e license_file=~/LatestV3DemoLicense.txt playbooks/license.yml

    - name: get the list of licenses, filter for description
      run_once: yes
      shell: sudo -u mapr maprcli license list -json | grep 'description":' | grep -v Base
      register: license_descriptions
      failed_when: license_descriptions.rc not in (0,1)
      changed_when: false

    - name: install a license key
      command: maprcli license add -license '{{ lookup('file', license_file) }}'
      sudo_user: mapr
      run_once: yes
      notify: 
        - start NFS gateways
        - start standby CLDBs
      when: inventory_hostname == groups["cldb"][0] and license_descriptions.rc == 1 # grep returned 1, so no non-Base license found

