---
# handlers file for mapr_license

    - name: start NFS gateways
      run_once: yes
      become: yes
      become_user: '{{mapr_admin_username}}'
      command: maprcli node services -action start -name nfs -filter csvc==nfs
      when: nfs_enabled is defined and nfs_enabled == True

    - name: start standby CLDBs
      run_once: yes
      become: yes
      become_user: mapr
      command: maprcli node services -action start -name cldb -filter csvc==cldb
